In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv("/content/movies_metadata.csv", low_memory=False, on_bad_lines='skip')

In [8]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [10]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [11]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [12]:
df = df.drop_duplicates().reset_index(drop = True)

In [13]:
#selects only the relevant columns from the original DataFrame.
#it trims the dataset down to key movie features (metadata + popularity metrics)to make analysis cleaner, faster, and more focused.
df = df[['title','overview','genres','tagline','vote_average','popularity']]
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [14]:
#filling nan in relevant cols
df = df.dropna(subset=['title'])
df['overview'] = df['overview'].fillna('')
df['tagline'] = df['tagline'].fillna('')
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [15]:
#convert 'genres' from stringified list of dicts to a single string of genre names
import ast
df['genres'] = df['genres'].apply(lambda x :''.join([i['name']for i in ast.literal_eval(x)]))

In [16]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",AnimationComedyFamily,,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,AdventureFantasyFamily,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,RomanceComedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",ComedyDramaRomance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [17]:
#create a 'tags' column by combining overview, genres, and tagline into a single text string
df['tags']=df['overview']+''+df['genres']+''+df['tagline']
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",AnimationComedyFamily,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,AdventureFantasyFamily,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,RomanceComedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",ComedyDramaRomance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [18]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [19]:
#download necessary NLTK resources
nltk.download('stopwords') #common words like 'the', 'is', 'and' that usually get removed
nltk.download('wordnet')   #dictionary for lemmatization

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [20]:
#prepare tools for text preprocessing
stop_words = set(stopwords.words('english')) #set of words to ignore
lemmatizer = WordNetLemmatizer()             #tool to reduce words to their base form

In [21]:
def process_text(text):
    text = str(text).lower()  #converts to lowercase
    text = re.sub(r'[^a-zA-Z\s]', '', text)  #remove punctuation
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]  # remove stopwords & lemmatize
    return " ".join(words)  #combine cleaned words back into a single string

In [22]:
import ast

def parse_genres(x):
    try:
        #if x is already a list/dict, just use it
        if isinstance(x, list):
            return ' '.join([i['name'] for i in x])
        #if x is a string representing list/dict
        elif isinstance(x, str):
            data = ast.literal_eval(x)
            return ' '.join([i['name'] for i in data])
        else:
            return ''  #empty string for malformed or missing data
    except:
        return ''  #fallback for any error

df['genres'] = df['genres'].apply(parse_genres)

df['tags'] = df['overview'].fillna('') + ' ' + df['genres'].fillna('') + ' ' + df['tagline'].fillna('')
df['tags'] = df['tags'].apply(process_text)

In [23]:
#reset index & create indices map ---
df = df.reset_index(drop=True)
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

In [24]:
#import the TfidfVectorizer class from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer
#keeps only the 5000 most significant words/bigrams to avoid a massive, sparse matrix
#considers both single words and pairs of consecutive words to capture context better
#moves common filler words so only meaningful words affect the model
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2), stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['tags']) #for machine learning models or similarity computations

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

#recommender function ---
def recommend(title, n=10):
#check if the movie exists in your dataset
    if title not in indices:
        return ['Movie not found']
    #get the index of the movie in your DataFrame
    idx = indices[title]
    #compute cosine similarity between this movie and all movies
    sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    #sort similarity scores in descending order, skip the first one (itself)
    similar_idx = sim_scores.argsort()[::-1][1:n+1]
    #return the titles of the top-n similar movies
    return df['title'].iloc[similar_idx].values

In [26]:
#Example usage ---
print(recommend('Toy Story'))

['Toy Story 2' 'Toy Reanimator'
 'Silent Night, Deadly Night 5: The Toy Maker' 'Hawaiian Vacation'
 'How the Toys Saved Christmas' "Don't Give a Damn" 'Toy Story of Terror!'
 'Motel Cactus' 'Dollman vs. Demonic Toys'
 'The Last Chance: Diary of Comedians']

In [27]:
print(recommend('The Dark Knight Rises'))

['Batman Forever' 'The Dark Knight' 'Slow Burn' 'Batman Returns'
 'Batman Unmasked: The Psychology of the Dark Knight'
 'Batman: Mask of the Phantasm' 'Accused' 'Night Falls on Manhattan'
 'LEGO DC Comics Super Heroes: Batman: Be-Leaguered' 'Rage of Angels']

In [28]:
!pip install -q sentence-transformers
from sentence_transformers import SentenceTransformer
import numpy as np

#load a pre-trained model (small & fast for now)
model = SentenceTransformer('all-MiniLM-L6-v2')

#encode all movie tags into embeddings
embeddings = model.encode(df['tags'].tolist(), show_progress_bar=True)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/1421 [00:00<?, ?it/s]

In [29]:
def semantic_recommend(title, n=10):
    if title not in indices:
        return ['Movie not found']

    idx = indices[title]
    movie_emb = embeddings[idx]

    #compute cosine similarity with all movies
    sim_scores = np.dot(embeddings, movie_emb) / (np.linalg.norm(embeddings, axis=1) * np.linalg.norm(movie_emb))

    #get top n similar movies (excluding itself)
    similar_idx = sim_scores.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx].values

In [30]:
print(semantic_recommend('Toy Story'))
print(semantic_recommend('The Dark Knight Rises'))

['Toy Story 3' 'Toy Story 2' 'Toy Reanimator' 'Firestarter'
 'Toy Story of Terror!' 'Hollywood Ending' "Andy Hardy's Blonde Trouble"
 'Sunspring' '1 Night' 'Hanging Garden']
['The Dark Knight' 'Batman Forever'
 'Batman: The Dark Knight Returns, Part 1' 'Batman Returns'
 'Batman: Mystery of the Batwoman' 'Batman Begins'
 'Batman Beyond: Return of the Joker' 'Batman Beyond: The Movie' 'Batman'
 'Batman v Superman: Dawn of Justice']

In [31]:
def recommend_by_genre_from_tags(user_genre, n=10):
    user_genre = user_genre.lower().strip()

    #filter movies whose 'tags' contain the genre keyword
    genre_filtered_df = df[df['tags'].str.contains(user_genre, case=False, na=False)]
# - case=False → ignore uppercase/lowercase
    # - na=False → skip rows where 'tags' is missing
    if genre_filtered_df.empty:
        return ['Genre not found']


    return genre_filtered_df['title'].head(n).values

In [32]:
print(recommend_by_genre_from_tags('Action'))

['Sudden Death' 'Mortal Kombat' 'Guardian Angel' 'Georgia'
 'Heidi Fleiss: Hollywood Madam' 'Taxi Driver'
 'Die Hard: With a Vengeance' 'Something to Talk About' 'Love Affair'
 "Mary Shelley's Frankenstein"]

In [33]:
print(recommend_by_genre_from_tags('Animation'))

['The Secret Adventures of Tom Thumb' 'Frank and Ollie'
 'The Nightmare Before Christmas' 'Faust' 'Young Frankenstein'
 'Re-Animator' 'Fantasia 2000' 'Time Masters' 'Gandahar' 'Galaxina']

In [34]:
print(recommend_by_genre_from_tags('Romance'))

['The Crossing Guard' 'Angels and Insects' 'If Lucy Fell'
 'Up Close & Personal' 'Total Eclipse' 'Before Sunrise' 'Don Juan DeMarco'
 'I Love Trouble' 'Clean Slate' 'Much Ado About Nothing']

#i switch from TF-IDF(Term Frequency, Inverse Document Frequency) to SentenceTransformer embeddings because:
#TF-IDF only captures word overlap, missing semantic meaning
#Transformers capture meaning/context of the tags
#Cosine similarity on embeddings gives smarter, context-aware recommendations